name: "Podcast Feeder"
author: "Randy Macdonald"
description: "Generate a podcast feed for a podcast from a YAML file."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "red"
  icon: "git-branch"
inputs:
  email:
    description: Commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: Commiter's name
    required: true
    default: ${{ github.actor }}
